name: Release

permissions:
  contents: write

env:
  DUCKDB_VERSION: 1.0.0

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install zig
        run: |
          sudo snap install zig --classic --edge

      - name: pre-build
        run: |
          echo "commit: $(git rev-parse HEAD | tr -d '\n')" > src/version.txt
          echo "zig: $(zig version)" >> src/version.txt

      - name: x86_64-linux-gnu
        run: |
          wget -q "https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/libduckdb-linux-amd64.zip"
          unzip -n *.zip && rm *.zip

          mkdir -p release/duckdb-proxy-x86_64-linux-gnu/
          zig build -Dtarget=x86_64-linux-gnu -Dcpu=x86_64_v2 -Doptimize=ReleaseFast
          mv libduckdb.so zig-out/bin/duckdb-proxy release/duckdb-proxy-x86_64-linux-gnu/

          cd release
          tar -cJf duckdb-proxy-x86_64-linux-gnu.tar.xz duckdb-proxy-x86_64-linux-gnu

      - name: aarch64-macos
        run: |
          wget -q "https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/libduckdb-osx-universal.zip"
          unzip -n *.zip && rm *.zip

          mkdir -p release/duckdb-proxy-aarch64-macos/
          zig build -Dtarget=aarch64-macos -Doptimize=ReleaseFast
          cp libduckdb.dylib zig-out/bin/duckdb-proxy release/duckdb-proxy-aarch64-macos/

          cd release
          tar -cJf duckdb-proxy-aarch64-macos.tar.xz duckdb-proxy-aarch64-macos

      - name: x86_64-macos
        run: |
          mkdir -p release/duckdb-proxy-x86_64-macos/
          zig build -Dtarget=x86_64-macos -Doptimize=ReleaseFast
          mv libduckdb.dylib zig-out/bin/duckdb-proxy release/duckdb-proxy-x86_64-macos/

          cd release
          tar -cJf duckdb-proxy-x86_64-macos.tar.xz duckdb-proxy-x86_64-macos

      - name: x86_64-windows
        run: |
          wget -q "https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/libduckdb-windows-amd64.zip"
          unzip -n *.zip && rm *.zip

          mkdir -p release/duckdb-proxy-x86_64-windows-gnu/
          zig build -Dtarget=x86_64-windows -Doptimize=ReleaseFast
          mv duckdb.dll zig-out/bin/duckdb-proxy.exe release/duckdb-proxy-x86_64-windows-gnu/

          cd release
          zip -r duckdb-proxy-x86_64-windows-gnu.zip duckdb-proxy-x86_64-windows-gnu

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /home/runner/work/duckdb-proxy/duckdb-proxy/release/duckdb-proxy-x86_64-linux-gnu.tar.xz
            /home/runner/work/duckdb-proxy/duckdb-proxy/release/duckdb-proxy-aarch64-macos.tar.xz
            /home/runner/work/duckdb-proxy/duckdb-proxy/release/duckdb-proxy-x86_64-macos.tar.xz
            /home/runner/work/duckdb-proxy/duckdb-proxy/release/duckdb-proxy-x86_64-windows-gnu.zip
